# Profile mặc định khi chạy test
spring.profiles.active=h2

# Server
server.port=8080

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Downstream URL for retry client
payment.downstream.url=http://localhost:8080
